/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f411ceu6_generic.h"

void delay() {
	for (volatile int i = 0; i < 100000; i++) {

	}
}

int main(void) {
	/* Loop forever */
	GPIO_HANDLE gpioB;
	gpioB.pGPIO = GPIOB;
	gpioB.GPIO_PIN_NUMBER = 12;
	gpioB.GPIO_MODE = OUTPUT;
	gpioB.GPIO_OUTPUT_TYPE = PUSHPULL;
	gpioB.GPIO_OUTPUT_SPEED = HIGH_SPEED;
	initGPIO(&gpioB);
	while (1) {
		GPIO_write(GPIOB, 12, HIGH);
//		delay();
		GPIO_write(GPIOB, 12, LOW);
//		delay();
	}
}
